from flask import Flask
from flask_mysqldb import MySQL

app = Flask(__name__)

app.jinja_env.filters['zip']=zip

## configuration of database

app.config["MYSQL_USER"] = 'oktazooka'
app.config["MYSQL_PASSWORD"] = 'peponi123!'
app.config["MYSQL_DB"] = 'test_db'
app.config["MYSQL_HOST"] = ''
app.config["SECRET_KEY"] = 'dbdbdbdb' ## secret key for sessions (signed cookies). Flask uses it to protect the contents of the user session against tampering.
app.config["WTF_CSRF_SECRET_KEY"] = '' ## token for csrf protection of forms.
## secret keys can be generated by secrets.token_hex()

## initialize database connection object
db = MySQL(app)

## routes must be imported after the app object has been initialized
import Routes
